app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("url_shortener.urls", namespace="url_shortener")),
    path("user/", include("user.urls", namespace="user")),

    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/doc/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/doc/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),

    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

url_shortener/urls.py
from django.urls import path

from url_shortener.views import RedirectView, UrlViewSet, IndexView

url_list = UrlViewSet.as_view({
    'get': 'list',
    'post': 'create',
})

url_detail = UrlViewSet.as_view({
    'get': 'retrieve',
    'post': 'partial_update',
})

url_delete = UrlViewSet.as_view({
    'post': 'destroy',
})

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("urls/", url_list, name="url-list"),
    path("urls/<int:pk>/", url_detail, name="url-detail"),
    path("urls/<int:pk>/delete/", url_delete, name="url-delete"),
    path("<str:slug>/", RedirectView.as_view(), name="redirect"),
]

app_name = "url_shortener"

url_shortener/models.py
from django.conf import settings
from django.db import models


class URL(models.Model):
    original_link = models.URLField(max_length=1000)
    short_url = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    num_visits = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="urls")

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "Urls"

    def __str__(self):
        return self.original_link

url_shortener/views.py
import uuid

from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from url_shortener.models import URL
from url_shortener.serializers import URLSerializer, URLDetailSerializer


class IndexView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "url_shortener/index.html"

    def get(self, request):
        return Response()


class UrlViewSet(viewsets.ModelViewSet):
    queryset = URL.objects.all()
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "url_shortener/url_list.html"
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        if self.request.user.is_superuser:
            return self.queryset
        return self.queryset.filter(user=self.request.user)

    def get_template_names(self):
        if self.action in ["list", "create"]:
            template_name = self.template_name
        else:
            template_name = "url_shortener/url_detail.html"
        return [template_name]

    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        serializer = URLSerializer()
        return Response({'url_list': queryset, 'serializer': serializer})

    def create(self, request, *args, **kwargs):
        serializer = URLSerializer(data=request.data)
        if not serializer.is_valid():
            return Response({'serializer': serializer})
        short_url = "localhost:8000/" + str(uuid.uuid4())[:5]
        serializer.save(short_url=short_url, user=request.user)
        return redirect('url_shortener:url-list')

    def retrieve(self, request, *args, **kwargs):
        url = self.get_object()
        serializer = URLDetailSerializer(url)
        return Response({'serializer': serializer, 'url': url})

    def partial_update(self, request, *args, **kwargs):
        url = self.get_object()
        serializer = URLDetailSerializer(url, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return redirect('url_shortener:url-detail', pk=url.pk)

    def destroy(self, request, *args, **kwargs):
        url = self.get_object()
        url.delete()
        return redirect('url_shortener:url-list')


class RedirectView(APIView):
    permission_classes = (AllowAny,)

    @staticmethod
    def redirect(request, slug):
        url = URL.objects.get(short_url=f"localhost:8000/{slug}")
        url.num_visits += 1
        url.save()
        return HttpResponseRedirect(redirect_to=url.original_link)

    def get(self, request, slug):
        return self.redirect(request, slug)

templates/url_shortener/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Url Shortener Home</h1>
  <h2>How use service:</h2>
  <ul>
        <li><strong>At first you must log in or sign up</strong></li>
        <li><strong>Unauthorized users can only follow the created links</strong></li>
        <li><strong>All other functionality you can see on
          <a href="{% url 'swagger-ui' %}">swagger documentation</a>
        </strong></li>
    </ul>
{% endblock %}

templates/url_shortener/url_detail.html
{% extends "base.html" %}
{% load rest_framework %}

{% block content %}
  <h1>
    Url Detail


    <form action="{% url 'url_shortener:url-delete' pk=url.pk %}" method="POST" class="link-to-page">
      {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
  </h1>

  <p><strong>Created:</strong> {{ url.created_at }}</p>
  <p><strong>Visits:</strong> {{ url.num_visits }}</p>
  <p><strong>User:</strong> {{ url.user.email }}</p>

  <form action="{% url 'url_shortener:url-detail' pk=url.pk %}" method="POST"><strong>
    {% csrf_token %}
    {% render_form serializer %}
    <input type="submit" value="Update" class="btn btn-primary">
  </strong></form>
{% endblock %}

templates/url_shortener/url_list.html
{% extends "base.html" %}
{% load rest_framework %}

{% block content %}
  <h1>
    Urls List
  </h1>

  <form action="{% url 'url_shortener:url-list' %}" method="POST" class="form-inline">
    {% csrf_token %}
    {% render_form serializer %}
    <input type="submit" value="Shorten" class="btn btn-secondary">
  </form>

  <br>

  {% if url_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Original link</th>
        <th>Short link</th>
        <th>Created</th>
        <th>Visits</th>
        <th>Update</th>
      </tr>

      {% for url in url_list %}
        <tr>
          <td>
              {{ url.id }}
          </td>
          <td>
              {{ url.original_link }}
          </td>
          <td>
              {{ url.short_url }}
          </td>
          <td>
              {{ url.created_at }}
          </td>
          <td>
              {{ url.num_visits }}
          </td>
          <td>
            <a href="{% url 'url_shortener:url-detail' pk=url.id %}">
              Update
            </a>
          </td>

        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are not your short links.</p>
  {% endif %}
{% endblock %}