app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("url_shortener.urls", namespace="url_shortener")),
    path("user/", include("user.urls", namespace="user")),

    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/doc/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/doc/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),

    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

url_shortener/urls.py
from django.urls import path

from url_shortener.views import RedirectView, UrlViewSet, IndexView

url_list = UrlViewSet.as_view({
    'get': 'list',
    'post': 'create',
})

url_detail = UrlViewSet.as_view({
    'get': 'retrieve',
    'post': 'partial_update',
})

url_delete = UrlViewSet.as_view({
    'post': 'destroy',
})

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("urls/", url_list, name="url-list"),
    path("urls/<int:pk>/", url_detail, name="url-detail"),
    path("urls/<int:pk>/delete/", url_delete, name="url-delete"),
    path("<str:slug>/", RedirectView.as_view(), name="redirect"),
]

app_name = "url_shortener"

user/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from user.views import CreateUserView, ManageUserView

urlpatterns = [
    path("register/", CreateUserView.as_view(), name="create"),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("me/", ManageUserView.as_view(), name="manage"),
]

app_name = "user"

templates/includes/sidebar.html
<div class="list-group">
  {% if user.is_authenticated %}
    <a href="{% url 'user:manage' %}" class="list-group-item list-group-item-action active">User: {{ user.email }}</a>
  {% else %}
    <a href="{% url 'user:token_obtain_pair' %}" class="list-group-item list-group-item-action active">Login</a>
    <a href="{% url 'user:create' %}" class="list-group-item list-group-item-action">Sign up</a>
  {% endif %}
</div>

<br>

<div class="list-group">
  <a href="{% url 'url_shortener:url-list' %}" class="list-group-item list-group-item-action">All urls</a>
</div>